services:

  ibkr_gateway:
    build:
      context: ./ibkr_gateway
    ports:
      - "5055:5055"
      - "5056:5056"
    networks:
      - trader
    environment:
      IBKR_ACCOUNT_ID: "U1234567"

#  nginx_proxy_manager:
#    image: 'jc21/nginx-proxy-manager:latest'
#    restart: always
#    ports:
#      - "80:80"    # HTTP
#      - "81:81"    # Admin UI
#      - "443:443"  # HTTPS
#    environment:
#      DB_SQLITE_FILE: "/data/database.sqlite"
#    volumes:
#      - npm_data:/data
#      - npm_letsencrypt:/etc/letsencrypt
#    networks:
#      - trader
#    depends_on:
#      - ibkr_gateway

  nginx:
    build:
      context: ./nginx
    environment:
      CERTBOT_EMAIL: david.a.gorski@gmail.com
      DOMAIN_LIST:  qa-dg-quant-trader.com
    restart: always
    depends_on:
      - ibkr_gateway
    volumes:
      - ./nginx/default_qa.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - trader

volumes:
  letsencrypt:
#  npm_data:
#  npm_letsencrypt:

networks:
  trader:
